services:
    db:
        image: ${DB_IMAGE:-mariadb:10.5}
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: koha_kohadev
            MYSQL_USER: koha_kohadev
            MYSQL_PASSWORD: password
        networks:
            - kohanet
    koha:
        image: koha/koha-testing:${KOHA_IMAGE}
        depends_on:
            - db
            - memcached
        cap_add:
            - ALL
        volumes:
            - ${SYNC_REPO}:/kohadevbox/koha
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - .env
        environment:
            COVERAGE: ${COVERAGE}
            CPAN: ${CPAN:-no}
            RUN_TESTS_AND_EXIT: ${RUN_TESTS_AND_EXIT}
            LOCAL_USER_ID: ${LOCAL_USER_ID}
            TEST_SUITE: ${TEST_SUITE:-light}
            TESTS_TO_RUN: ${TESTS_TO_RUN:-""}
            TEST_DB_UPGRADE: ${TEST_DB_UPGRADE:-no}
            KOHA_ELASTICSEARCH: ${KOHA_ELASTICSEARCH:-no}
            SKIP_CYPRESS_CHOWN: ${SKIP_CYPRESS_CHOWN:-no}
            SKIP_L10N: ${SKIP_L10N:-no}
            KOHA_IMAGE: ${KOHA_IMAGE:-main}
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            proxy:
                aliases:
                    - "${KOHA_INTRANET_PREFIX}${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}"
                    - "${KOHA_OPAC_PREFIX}${KOHA_INSTANCE}${KOHA_OPAC_SUFFIX}${KOHA_DOMAIN}"
            kohanet:
                aliases:
                    - "${KOHA_INTRANET_PREFIX}${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}"
                    - "${KOHA_OPAC_PREFIX}${KOHA_INSTANCE}${KOHA_OPAC_SUFFIX}${KOHA_DOMAIN}"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.${KOHA_INSTANCE}-intra.rule=Host(`${KOHA_INTRANET_PREFIX}${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}`) || Host(`${KOHA_INSTANCE}-intra.localhost`)"
            - "traefik.http.routers.${KOHA_INSTANCE}-intra.entrypoints=web"
            - "traefik.http.routers.${KOHA_INSTANCE}-intra.service=${KOHA_INSTANCE}-intra"
            - "traefik.http.services.${KOHA_INSTANCE}-intra.loadbalancer.server.port=8081"
            - "traefik.http.routers.${KOHA_INSTANCE}-opac.rule=Host(`${KOHA_OPAC_PREFIX}${KOHA_INSTANCE}${KOHA_OPAC_SUFFIX}${KOHA_DOMAIN}`) || Host(`${KOHA_INSTANCE}.localhost`)"
            - "traefik.http.routers.${KOHA_INSTANCE}-opac.entrypoints=web"
            - "traefik.http.routers.${KOHA_INSTANCE}-opac.service=${KOHA_INSTANCE}-opac"
            - "traefik.http.services.${KOHA_INSTANCE}-opac.loadbalancer.server.port=8080"
    memcached:
        image: ${MEMCACHED_IMAGE:-memcached}
        command: memcached -m 64m
        networks:
            - kohanet

networks:
    kohanet:
    proxy:
        external: true

